# Generated by Django 5.1.2 on 2024-10-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_number', models.PositiveIntegerField()),
                ('F_name', models.CharField(max_length=60)),
                ('L_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=70)),
                ('gpa', models.FloatField()),
            ],
        ),
    ]
